[package]
name = "mvtrans"
version = "0.3.0"
authors = ["Connor"]

[dependencies]
serde_json = "~1.0"
clap = "~2.31"

[dev-dependencies]
tempfile = "3"
pretty_assertions = "0.5.1"

[dependencies.rusqlite]
version = "~0.13.0"
features = ["bundled"]